name: AllTheThings
version: "1.0"
description: "It's a suggest mode for both pages *and* entries."
url: https://github.com/LionsMouthDigital/statamic-all-the-things
developer: Curtis Blackwell
developer_url: https://lionsmouth.digital
